### PR TITLE
patch for bug with activerecord-session_store gem

### PR DESCRIPTION
**Pull request by JonathanAndrews**
Patch for issue #40 

Without the 'activerecord-session_store' gem, `env['rack.session']` stores the keys as strings.
With the gem, `env[rack.session]` stores the keys as they are entered.

This fix is call  `with_indifferent_access`on the `balrog_session`.

### CODE REVIEW

**Comment by jalada** [comment]
Happy with this! @JonathanAndrews were the tests failing before you made this change, once you added AR session store?

**Comment by JonathanAndrews** [comment]
> Happy with this! @JonathanAndrews were the tests failing before you made this change, once you added AR session store?

@jalada No, the tests should pass.
I've updated the README with more info on running the tests.

**Comment by JonathanAndrews** [comment]
Yes, once I had added the session store gem, the tests failed.
To get them to pass again, I added `balrog_session&.with_indifferent_access`.

**Comment by jalada** [comment]
Great!

**Pull request merged**
